### ISSUE TITLE
instance we create for stealDChashes needs a vpc

### ISSUE THREAD

**Issue by carnal0wnage** [Static-Flow/CloudCopy#3]
instance we create for stealDChashes needs a vpc  and it fails

An error occurred (VPCResourceNotSpecified) when calling the RunInstances operation: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
Connecting to instance
Traceback (most recent call last):
  File "CloudCopy.py", line 290, in <module>
    cmd.cmdloop()
  File "CloudCopy.py", line 39, in cmdloop
    return super(BaseCmdInterpreter, self).cmdloop()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "CloudCopy.py", line 276, in do_profile_cloudcopy
    sub_cmd.cmdloop()
  File "CloudCopy.py", line 39, in cmdloop
    return super(BaseCmdInterpreter, self).cmdloop()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "CloudCopy.py", line 165, in do_stealDCHashes
    self.cloudCopier.stealDCHashFiles()
  File "/Users/CG/Downloads/lab/CloudCopy/CloudCopyUtils.py", line 270, in stealDCHashFiles
    connection, sftp = self.connectToInstance()
  File "/Users/CG/Downloads/lab/CloudCopy/CloudCopyUtils.py", line 257, in connectToInstance
    connection.connect(hostname=self.attackingInstance.public_dns_name, username='ec2-user', pkey=key)
AttributeError: 'NoneType' object has no attribute 'public_dns_name'

**Comment by carnal0wnage** [comment]
Ok i did get this working. you have to create a VPC and subnet - i added the following lines to get this working in hurry.

I manually created in the UI the vpc and subnet and added that value in CloudCopyUtils.py for the _createInstance function

```
 NetworkInterfaces = [
            {   
            'SubnetId': 'subnet-0XXXXXXXXc',
            'DeviceIndex': 0,
            'AssociatePublicIpAddress': True,
            'Groups': [self.securityGroup.group_id]
            }
            ]
```

**Comment by Static-Flow** [comment]
I'll look into this for sure. It should be creating those for you, if it doesn't they're easy to make. Thanks for the bug report!

**Comment by Static-Flow** [comment]
So I finally got around to working on this. The tool now tries to live off the land by using existing infrastructure that has the right rules. If that's not possible it will create a VPC internet gateway, subnet, and security group. Should fix this issue.
